spring:
  application:
    name: api
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: api
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 60000

turnstile:
  secret-key: ${TURNSTILE_SECRET_KEY}

app:
  base-url: https://www.runmarket.cc
  mail:
    from: noreply@mail.runmarket.cc
  verification:
    token-expiry-minutes: 30
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  seoul-air-district:
    url: http://openAPI.seoul.go.kr:8088/${SEOUL_API_KEY}/json/ListAirQualityByDistrictService/1/20/
    fallback-url: https://gist.githubusercontent.com/GHGHGHKO/d668b7dc3fc397d36b4be38756118184/raw/3e9069422872b612e5c49fc36ac8813d2cbe5c7f/air.json
  llm:
    url: http://ollama.ollama.svc.cluster.local:11434
    model: gemma4:e2b
